### ISSUE TITLE
Add example for passing a list

### ISSUE THREAD

**Issue by nobe4** [GrantBirki/comment#11]
Hi 👋 

I found out today how to pass a list of arguments via the variables. I struggled a bit and this solution could be beneficial for others, in case you want to add it to the readme/docs.

Here's the setup:

```yml

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - id: run
        run:  echo "files=a,b,c" >> "$GITHUB_OUTPUT"

      - uses: GrantBirki/comment
        with:
          # other config
          vars: |
            files: ${{ steps.run.outputs.files }}
          body: |
            # Files
            {% for file in files.split(",") %}
            - `{{ file }}`
            {% else %}
            - No file
            {% endfor %}
```

What's important here is to serialize the `files` list when passing between steps. Passing a multiline-string breaks the `vars` value.

Thanks ✨
