### ISSUE TITLE
feature request: support addint reactions to PR reviews / PR review comments

### ISSUE THREAD

**Issue by bryangingechen** [GrantBirki/comment#7]
Currently, there are various ways to leave comment-like messages on GitHub PRs:
- [PR comments](https://docs.github.com/en/rest/issues/comments)
- [PR reviews](https://docs.github.com/en/rest/pulls/reviews)
- [PR review comments](https://docs.github.com/en/rest/pulls/comments)

For our particular use-case, we'd like to be able to add reactions to all 3 of these types, but it seems that this action doesn't currently support PR reviews / PR review comments.

The following minimized workflow attempts to add a reaction to a PR review comment:
```
on:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  add_reaction:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: GrantBirki/comment@v2.0.1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
```

However, it fails with:

> Adding reaction 'rocket' to comment id 'XXXX' failed with HttpError: Not Found.
